declare global {
	interface Window {
		__env: EnvironmentVariables
	}
}

interface EnvironmentVariables {
	NEXT_PUBLIC_LOGOUT: string
	NEXTAUTH_URL: string
    NEXT_PUBLIC_API_ENDPOINT: string
	NEXT_PUBLIC_BPMNSERVICE_URL: string
    NEXT_PUBLIC_GET_FIREWALLS: string
	NEXT_PUBLIC_EDIT_FIREWALL_RULES: string
	NEXT_PUBLIC_GET_FIREWALL_REQUESTS: string
	NEXT_PUBLIC_CREATE_FIREWALL_REQUEST: string
	NEXT_PUBLIC_EDIT_FIREWALL_REQUEST: string
	NEXT_PUBLIC_FIREWALL_REQUEST: string
	NEXT_PUBLIC_GET_USER: string
	NEXT_PUBLIC_CREATE_USER: string
	NEXT_PUBLIC_BPMN_GET_PROCESS_INSTANCE: string
	NEXT_PUBLIC_BPMN_GET_PROCESS_DEFINITION: string
	NEXT_PUBLIC_BPMN_GET_TASK: string
	AZURE_AD_CLIENT_ID: string
	AZURE_AD_CLIENT_SECRET: string
	AZURE_AD_TENANT_ID: string
	MONGODB_URI: string
	NEXT_PUBLIC_HETZNER_FIREWALLS: string
	NEXT_PUBLIC_HETZNER_API_TOKEN: string
	NEXT_PUBLIC_X_API_KEY: string
}

const defaultBuildValues: EnvironmentVariables = {
	NEXT_PUBLIC_LOGOUT: process.env.NEXT_PUBLIC_LOGOUT ?? '',
	NEXTAUTH_URL: process.env.NEXTAUTH_URL ?? '',
	NEXT_PUBLIC_API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT ?? '',
	NEXT_PUBLIC_BPMNSERVICE_URL: process.env.NEXT_PUBLIC_BPMNSERVICE_URL ?? '',
    NEXT_PUBLIC_GET_FIREWALLS: process.env.NEXT_PUBLIC_GET_FIREWALLS ?? '',
	NEXT_PUBLIC_EDIT_FIREWALL_RULES: process.env.NEXT_PUBLIC_EDIT_FIREWALL_RULES ?? '',
	NEXT_PUBLIC_GET_FIREWALL_REQUESTS:  process.env.NEXT_PUBLIC_GET_FIREWALL_REQUESTS ?? '',
	NEXT_PUBLIC_CREATE_FIREWALL_REQUEST: process.env.NEXT_PUBLIC_CREATE_FIREWALL_REQUEST ?? '',
	NEXT_PUBLIC_EDIT_FIREWALL_REQUEST: process.env.NEXT_PUBLIC_EDIT_FIREWALL_REQUEST ?? '',
	NEXT_PUBLIC_FIREWALL_REQUEST: process.env.NEXT_PUBLIC_FIREWALL_REQUEST ?? '',
	NEXT_PUBLIC_GET_USER: process.env.NEXT_PUBLIC_GET_USER ?? '',
	NEXT_PUBLIC_CREATE_USER: process.env.NEXT_PUBLIC_CREATE_USER ?? '',
	NEXT_PUBLIC_BPMN_GET_PROCESS_INSTANCE: process.env.NEXT_PUBLIC_BPMN_GET_PROCESS_INSTANCE ?? '',
	NEXT_PUBLIC_BPMN_GET_PROCESS_DEFINITION: process.env.NEXT_PUBLIC_BPMN_GET_PROCESS_DEFINITION ?? '',
	NEXT_PUBLIC_BPMN_GET_TASK: process.env.NEXT_PUBLIC_BPMN_GET_TASK ?? '',
	AZURE_AD_CLIENT_ID: process.env.AZURE_AD_CLIENT_ID ?? '',
	AZURE_AD_CLIENT_SECRET: process.env.AZURE_AD_CLIENT_SECRET ?? '',
	AZURE_AD_TENANT_ID: process.env.AZURE_AD_TENANT_ID ?? '',
	MONGODB_URI: process.env.MONGODB_URI ?? '',
	NEXT_PUBLIC_HETZNER_FIREWALLS: process.env.NEXT_PUBLIC_HETZNER_FIREWALLS ?? '',
	NEXT_PUBLIC_HETZNER_API_TOKEN: process.env.NEXT_PUBLIC_HETZNER_API_TOKEN ?? '',
	NEXT_PUBLIC_X_API_KEY: process.env.X_API_KEY ?? ''
}

export const ENV = Object.freeze(defaultBuildValues) 